server:
  port: 8090
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/neo
    username: neo
    password: neo
    driverClassName: org.postgresql.Driver
